Repository hikaya-io/activity, pull requests merged in 2020-05, with the labels that each got.

#601 Fix linting errors
  activity/urls.py
  activity/views.py
  ci-scripts/run_tests.sh
  configurabledashboard/admin.py
  configurabledashboard/models.py
  configurabledashboard/views.py
  customdashboard/admin.py
  customdashboard/models.py
  customdashboard/views.py
  formlibrary/serializers.py
  formlibrary/views.py
  indicators/forms.py
  indicators/management/commands/create_targets.py
  indicators/management/commands/lop.py
  indicators/management/commands/update_indicators.py
  indicators/serializers.py
  indicators/urls.py
  indicators/views.py
  pylintrc
  requirements.txt
  setup.cfg
  workflow/forms.py
  workflow/management/commands/upload_sites.py
  workflow/models.py
  workflow/views.py
Labels: 1, refactor

#623 ISS-620: Fix image build error on staging
  ci-scripts/build_docker_image.sh
  ci-scripts/create_infrastructure.sh
  ci-scripts/deployment.sh
Labels: defect

#618 add checklistitem tests
  workflow/tests/models/__init__.py
  workflow/tests/models/test_checklist.py
  workflow/tests/models/test_project.py
  workflow/tests/models/test_site_profile.py
Labels: tests
